version = 0.1
    [default]
    [default.deploy]
    [default.deploy.parameters]
    stack_name = "react-static-site"
    resolve_s3 = true
    confirm_changeset = false
    capabilities = "CAPABILITY_IAM"
    region = "us-east-1"
